### PR TITLE
Update to proposed angular mocks changes

### PR DESCRIPTION
**Pull request by dmaloneycalu**
- Merge commits from Angular master
- Adds `.whenRoute` and `.expectRoute` to `$httpBackend`

This should make it much easier to accept when creating the PR to Angular. Wanted to open this up here and will follow this with a PR to our Mocks repo that demonstrates the changes.

@vokal/web

### CODE REVIEW

**Comment by dmaloneycalu** [comment]
The changes I made are between line 1150 and 1750.

**Comment by Tathanen** [comment]
Does this get rid of the part where I have to do this:

`var params = $httpBackend.getParams( url, APIRoot + "contacts/:id" );`

And instead return those params as part of the `respond` signature?

**Comment by thoughtpalette** [comment]
:+1:

**Comment by dmaloneycalu** [comment]
@Tathanen yeah, params are now always included in the respond function.

```
$httpBackend.whenRoute( "GET", "/contacts/:id" )
    .respond( function ( method, url, data, headers, params )
    {
        // params contains { id: "<something>" } at the least
    } );

```

**Comment by Tathanen** [comment]
Nice!

LGTM

**Comment by dmaloneycalu** [comment]
Merging these here so we can reference these changes by the commit hash.

**Pull request merged**
