### PR TITLE
String based 'when' matching, respond function receives request object.

### PR DESCRIPTION
**Pull request by dmaloneycalu**
@Tathanen @jrit 

This PR should be thoroughly vetted before we move forward with it. Once this is approved I'll be starting this as a feature request with Angular directly. This fork of bower-angular-mocks allows us to use it in the meantime.

There's an associated PR in [voka-angular-mocks](https://github.com/vokal/vokal-angular-mocks) with these changes currently in use.

### CODE REVIEW

**Comment by Tathanen** [comment]
So, I know we like returning response objects, but maybe it's better to stick to angular convention here and just add "params" as an additional parameter in their function signature.  It's a little less breaking, and more inline with their existing standards.  Maybe more likely to get merged that way.

**Comment by jrit** [comment]
I think you might have to fork from angular master instead and update https://github.com/angular/angular.js/blob/master/test/ngMock/angular-mocksSpec.js to cover your changes

**Comment by dmaloneycalu** [comment]
@jrit What do you think about Cory's suggestion? Before it can be added to Angular, the code will have to be applied to the Angular source repo and tests coverage included. This repo is purely for our benefit in the meantime.

**Comment by jrit** [comment]
I agree with @Tathanen about the interface on `handleResponse` - I actually prefer your updated version, but it does seem like too much of an interface change for angular. In use, we could wrap it in something, but that would be outside this repo.

**Comment by dmaloneycalu** [comment]
Made the changes per @Tathanen's suggestion, updated the PR [here](https://github.com/vokal/vokal-angular-mocks/pull/4) as well.

**Comment by Tathanen** [comment]
LGTM

**Pull request merged**
